name: deployment
on:
  # for testing
  workflow_dispatch:
  # production
  push:
    branches:
      - main
jobs:
  dev_deployment:
    runs-on: ubuntu-latest
    name: Deploy to AWS Dev Environment
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_DEV_HOST }}
        username: ${{ secrets.AWS_DEV_USERNAME }}
        key: ${{ secrets.AWS_DEV_KEY }}
        port: ${{ secrets.AWS_DEV_PORT }}
        script: |
          /home/ec2-user/update-env.sh
